### ISSUE TITLE
Links on items gives unknown method

### ISSUE THREAD

**Issue by philsturgeon** [trainline/json-api-vanilla#4]
I have a basic collection, and each item has links:

``` json
{
  "data": [
    {
      "type": "thing",
      "id": "123",
      "links": {
        "foo": "https://example/foo",
        "bar": "https://example/bar"
      },
      "attributes": {
          "thing": "yep"
        }
      }
    },
    ....
}
```

Following your instructions, I would expect to be able to do this:

``` ruby
response = JSON::Api::Vanilla.parse(json)
things = response.data

things.first.links # { "foo": "https://example/foo", "bar": "https://example/bar"} 
```

The actual result is:

> *** NoMethodError Exception: undefined method `links' for #<#<Class:0x00007fdb9783a7f0>:0x00007fdb97839148>

Any suggestions?

**Comment by hovancik** [comment]
This might be the problem, but I guess further debugging is needed: https://github.com/trainline/json-api-vanilla/blob/master/lib/json-api-vanilla/parser.rb#L52

**Comment by Tolsee** [comment]
@philsturgeon Does not the `links` have special meaning in JSON Api specification?

**Comment by philsturgeon** [comment]
@Tolsee yes links is a thing and I was trying to access it. I no longer use this tool so cannot provide anymore information.
